spring.application.name=gestor-tareas

# ===============================
# = DATA SOURCE
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# = JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# = SERVER
# ===============================

server.port=8080

#=======================================
# secret key

jwt.secret=7jlqRk5t7COwMgiMEEhiHfm4MijJusDAXx1OAB9RKttXUxdr70Yp0PSrtnvWJu1
jwt.expiration=86400000
